name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
  AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
  AUTH0_PRIVATE_INV_TOKEN: ${{ secrets.AUTH0_PRIVATE_INV_TOKEN }}
  AUTH0_CLIENTID: ${{ secrets.AUTH0_CLIENTID }}
  SQL_CONN_STRING: ${{ secrets.SQL_CONN_STRING }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print Environment Variables
      run: |
        env
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
